spring:
  application:
    name: up
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:h2:file:./data/updb;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect

feign:
  example-api:
    url: ${EXAMPLE_API_URL:http://localhost:8080}
  upbit:
    base-url: ${UPBIT_API_URL:https://api.upbit.com}

logging:
  level:
    com.clone.up.client: DEBUG  # Feign 요청/응답 로그
