spring:
  application:
    name: up
  jackson:
    property-naming-strategy: SNAKE_CASE

feign:
  example-api:
    url: ${EXAMPLE_API_URL:http://localhost:8080}
  upbit:
    base-url: ${UPBIT_API_URL:https://api.upbit.com}

logging:
  level:
    com.clone.up.client: DEBUG  # Feign 요청/응답 로그
